# Übung 12 - Pandas Recap 3

Arbeiten Sie nachfolgenden Aufgabenstellungen durch und dokumentieren Sie, wenn notwendig, ihre Erkenntnisse.

In [1]:
import pandas as pd

## Task 12.1

Erstellen Sie a) das DataFrame `person_df` mit folgendem Inhalt:

<table>
    <tr><th></th><th>Gewicht</th><th>Größe</th></tr>
     <tr><td>Henry</td><td>75</td><td>179</td></tr>
    <tr><td>Sarah</td><td>68</td><td>165</td></tr>
    <tr><td>Elke</td><td>68</td><td>172</td></tr>
    <tr><td>Susi</td><td>55</td><td>164</td></tr>
    <tr><td>Vera</td><td>58</td><td>160</td></tr>
    <tr><td>Toni</td><td>99</td><td>189</td></tr>
    <tr><td>Maria</td><td>68</td><td>176</td></tr>
    <tr><td>Chris</td><td>60</td><td>175</td></tr>    
</table>

In [9]:
#a)
people = ["Henry", "Sarah", "Elke", "Susi", "Vera", "Toni", "Maria", "Chris"]
weight = [75, 68, 68, 55, 58, 99, 68, 60]
height = [179, 165, 172, 164, 160, 189, 176, 175]
hey = {
    "Name":people,
    "Gewicht": weight,
    "Größe":height
}
p_df = pd.DataFrame(hey)
p_df.set_index("Name", inplace=True)
p_df

       Gewicht  Größe
Name
Henry       75    179
Sarah       68    165
Elke        68    172
Susi        55    164
Vera        58    160
Toni        99    189
Maria       68    176
Chris       60    175

Der sog. *Body Mass Index* [1] berechnet sich durch Körpermasse [kg] / Körpergröß [m]². Berechnen Sie b) den BMI für alle Personen des DataFrames `person_df` und geben Sie ausschließlich jene aus, deren BMI > 20 und < 25 ist. 

**Hinweis**: Erstellen Sie KEINE neue Spalte im DataFrame. Es ist ausschließlich folgendes Ergebnis in der Zelle auszugeben:

```Python
Henry    23.407509 
Sarah    24.977043 
Elke     22.985398  
Susi     20.449137  
Vera     22.656250  
Maria    21.952479
dtype: float64
``` 
[1] https://de.wikipedia.org/wiki/Body-Mass-Index

In [16]:
# b - klassische Ansatz ohne apply & lambda)
p_df["Gewicht"]/p_df["Größe"]

Name
Henry    0.418994
Sarah    0.412121
Elke     0.395349
Susi     0.335366
Vera     0.362500
Toni     0.523810
Maria    0.386364
Chris    0.342857
dtype: float64

Nachdem die Berechnung erfolgreich war, fügen Sie c) die ermittelten Werte (je Person) dem DataFrame `person_df` hinzu. Als Spaltenname ist *BMI* zu wählen.

In [17]:
#c)
p_df["BMI"] = p_df["Gewicht"]/p_df["Größe"]
p_df

       Gewicht  Größe       BMI
Name
Henry       75    179  0.418994
Sarah       68    165  0.412121
Elke        68    172  0.395349
Susi        55    164  0.335366
Vera        58    160  0.362500
Toni        99    189  0.523810
Maria       68    176  0.386364
Chris       60    175  0.342857

Geben Sie d) das erzeugte DataFrame absteigend sortiert nach dem BMI aus.

In [20]:
#d)
p_df.sort_values(by="BMI",ascending=False,inplace=True)
p_df

       Gewicht  Größe       BMI
Name
Toni        99    189  0.523810
Henry       75    179  0.418994
Sarah       68    165  0.412121
Elke        68    172  0.395349
Maria       68    176  0.386364
Vera        58    160  0.362500
Chris       60    175  0.342857
Susi        55    164  0.335366

## Task 12.2

Laden Sie das bereitgestellte Dataset *parks.csv* und verschaffen Sie sich einen Überblick über dessen Aufbau bzw. Inhalt.

In [26]:
park_df = pd.read_csv("parks.csv")
park_df.head()

  Park Code               Park Name State   Acres  Latitude  Longitude
0      ACAD    Acadia National Park    ME   47390     44.35     -68.21
1      ARCH    Arches National Park    UT   76519     38.68    -109.57
2      BADL  Badlands National Park    SD  242756     43.75    -102.50
3      BIBE  Big Bend National Park    TX  801163     29.25    -103.25
4      BISC  Biscayne National Park    FL  172924     25.65     -80.08

a) Geben Sie den Park mit der ID 9 aus:

In [23]:
#a)
park_df.loc[9]

Park Code                              CAVE
Park Name    Carlsbad Caverns National Park
State                                    NM
Acres                                 46766
Latitude                              32.17
Longitude                           -104.44
Name: 9, dtype: object

b) Geben Sie Filme mit der ID 3, 12 und 24 aus:

In [28]:
#b)
park_df.loc[[3,12,24]]

,Park Code,Park Name,State,Acres,Latitude,Longitude
3,BIBE,Big Bend National Park,TX,801163,29.25,-103.25
12,CRLA,Crater Lake National Park,OR,183224,42.94,-122.10
24,GRSM,Great Smoky Mountains National Park,"TN, NC",521490,35.68,-83.53

c) Wie ist das DataFrame `park_df` zu ändern, dass die Abfrage `park_df.loc['BIBE']` durchläuft und somit folgendes Ergebnis liefert:

```Python
Park Name    Big Bend National Park
State                            TX
Acres                        801163
Latitude                      29.25
Longitude                   -103.25
Name: BIBE, dtype: object
```

In [31]:
#c)
park_df.set_index("Park Code", inplace=True)
park_df.loc['BIBE']

Park Name    Big Bend National Park
State                            TX
Acres                        801163
Latitude                      29.25
Longitude                   -103.25
Name: BIBE, dtype: object

d) Geben Sie die ersten drei sowie den 4., 5. und 6 Park aus (zwei separate Anfragen mit `iloc`):

In [34]:
#d)
print(park_df.iloc[:3])
park_df.iloc[4:6]

                        Park Name State   Acres  Latitude  Longitude
Park Code
ACAD         Acadia National Park    ME   47390     44.35     -68.21
ARCH         Arches National Park    UT   76519     38.68    -109.57
BADL       Badlands National Park    SD  242756     43.75    -102.50

,Park Name,State,Acres,Latitude,Longitude
Park Code,,,,,
BISC,Biscayne National Park,FL,172924,25.65,-80.08
BLCA,Black Canyon of the Gunnison National Park,CO,32950,38.57,-107.72

e) Gesucht ist folgende Ausgabe der Spalte *Park Code*:

```Python
0    ACAD
1    ARCH
2    BADL
Name: Park Code, dtype: object
```

In [56]:
#e)
park_df.iloc[:3]

                        Park Name State   Acres  Latitude  Longitude
Park Code
ACAD         Acadia National Park    ME   47390     44.35     -68.21
ARCH         Arches National Park    UT   76519     38.68    -109.57
BADL       Badlands National Park    SD  242756     43.75    -102.50

Spaltennamen mit Leerzeichen (und Großbuchstaben) sind eine potenzielle Fehlerquelle, die es zu eliminieren gilt. Ändern Sie f) die Spaltennamen durch den Einsatz von `replace(...)` und `lower(...)` in einer *List Comprehension*. **Wichtig**: Die Liste mit den neuen Spaltennamen ist in der *List Comprehension* zu erstellen. Warum wir eine Liste benötigen, ist durch das Property *columns* von *DataFrame* definiert. `new_column_names` gestaltet sich nach Abarbeitung der *List Comprehension* wie folgt:

```Python
['parkcode', 'parkname', 'state', 'acres', 'latitude', 'longitude']
```

In [66]:
#f) Neue Spaltennamen

Selektieren Sie g) den Parknamen und den Bundestaat der ersten 3 Zeilen im *DataFrame*.

In [15]:
#g)

h) Worin unterscheiden Sie diese beiden Abfragen und was wäre eine logische Erklärung dafür?
- `park_df.iloc[2]`
- `park_df.iloc[[2]]`

In [16]:
# h)

i) Welche Parks befinden sich im Bundesstaat Utah (UT)?

In [68]:
#i)
park_df.loc["state"]

KeyError: 'state'

j) Welche Parks erfüllen folgende Bedingung? 
- latitude > 60 oder acres > 1000000

In [18]:
#j)

k) Finden Sie alle Parks, die sich in den Bundesstaaten *WA*, *OR* und *CA* befinden. Verwenden Sie hierzu `isin()` (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isin.html?highlight=isin#pandas.DataFrame.isin)

In [19]:
#k)